name: Build and push docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: harbor-b.alauda.cn
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: build and push image
        run: |
          docker build -t harbor-b.alauda.cn/ait/kubernetes-event-exporter:v1.0 . && \
          docker push harbor-b.alauda.cn/ait/kubernetes-event-exporter:v1.0
      - name: docker login armharbor
        uses: azure/docker-login@v1
        with:
          login-server: armharbor.alauda.cn
          username: ${{ secrets.ARM_REGISTRY_USERNAME }}
          password: ${{ secrets.ARM_REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: build and push arm image
        run: |
          docker buildx build --platform linux/arm64 -t armharbor.alauda.cn/ait/kubernetes-event-exporter:v1.0 --push .
