name: Build and push docker image
#on:
#  push:
#    branches:
#      - master
on: [push]

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker login
        uses: azure/docker-login@v1
        with:
          login-server: index.alauda.cn
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: build and push image
        run: |
          docker build -t index.alauda.cn/claas/kubernetes-event-exporter:v1.0 . && \
          docker push index.alauda.cn/claas/kubernetes-event-exporter:v1.0
